### ISSUE TITLE
I can not get it to run

### ISSUE THREAD

**Issue by joanmarcriera** [joenan/person-frontend-application#1]
Hi, I'm running inside the following Vagrant machine : https://github.com/joanmarcriera/vagrant-file-for-java-apps

The error shows as follows : 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/@angular/compiler-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/karma/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ngx-input-tag@0.0.5 requires a peer of @angular/core@^5.0.0 but none was installed.
npm WARN ngx-input-tag@0.0.5 requires a peer of @angular/common@^5.0.0 but none was installed.
npm WARN ngx-input-tag@0.0.5 requires a peer of @angular/forms@^5.0.0 but none was installed.
npm WARN karma-jasmine-html-reporter@1.5.2 requires a peer of jasmine-core@>=3.5 but none was installed.
npm ERR! Linux 3.10.0-957.5.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! @angular/cli@8.2.2 postinstall: `node ./bin/postinstall/script.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular/cli@8.2.2 postinstall script 'node ./bin/postinstall/script.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @angular/cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/postinstall/script.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @angular/cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @angular/cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/person-frontend-application/npm-debug.log
[vagrant@localhost person-frontend-application]$

The last lines from the debug file are : 

155792 silly lifecycle socket.io@2.1.1~postinstall: no script for postinstall, continuing
155793 silly postinstall yn@2.0.0 /home/vagrant/person-frontend-application/node_modules/.staging/yn-ed505928
155794 info lifecycle yn@2.0.0~postinstall: yn@2.0.0
155795 silly lifecycle yn@2.0.0~postinstall: no script for postinstall, continuing
155796 silly postinstall @angular-devkit/build-angular@0.802.2 /home/vagrant/person-frontend-application/node_modules/.staging/@angular-devkit/build-angular-6181bff7
155797 info lifecycle @angular-devkit/build-angular@0.802.2~postinstall: @angular-devkit/build-angular@0.802.2
155798 silly lifecycle @angular-devkit/build-angular@0.802.2~postinstall: no script for postinstall, continuing
155799 silly postinstall @angular/animations@8.2.14 /home/vagrant/person-frontend-application/node_modules/.staging/@angular/animations-91b1207b
155800 info lifecycle @angular/animations@8.2.14~postinstall: @angular/animations@8.2.14
155801 silly lifecycle @angular/animations@8.2.14~postinstall: no script for postinstall, continuing
155802 silly postinstall @angular/cdk@8.2.3 /home/vagrant/person-frontend-application/node_modules/.staging/@angular/cdk-959dcee3
155803 info lifecycle @angular/cdk@8.2.3~postinstall: @angular/cdk@8.2.3
155804 silly lifecycle @angular/cdk@8.2.3~postinstall: no script for postinstall, continuing
155805 silly postinstall @angular/cli@8.2.2 /home/vagrant/person-frontend-application/node_modules/.staging/@angular/cli-3550d775
155806 info lifecycle @angular/cli@8.2.2~postinstall: @angular/cli@8.2.2
155807 verbose lifecycle @angular/cli@8.2.2~postinstall: unsafe-perm in lifecycle true
155808 verbose lifecycle @angular/cli@8.2.2~postinstall: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/vagrant/person-frontend-application/node_modules/@angular/cli/node_modules/.bin:/home/vagrant/person-frontend-application/node_modules/.bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.local/bin:/home/vagrant/bin
155809 verbose lifecycle @angular/cli@8.2.2~postinstall: CWD: /home/vagrant/person-frontend-application/node_modules/@angular/cli
155810 silly lifecycle @angular/cli@8.2.2~postinstall: Args: [ '-c', 'node ./bin/postinstall/script.js' ]
155811 silly lifecycle @angular/cli@8.2.2~postinstall: Returned: code: 1  signal: null
155812 info lifecycle @angular/cli@8.2.2~postinstall: Failed to exec postinstall script
155813 verbose unlock done using /home/vagrant/.npm/_locks/staging-d8fb262d67f9f226.lock for /home/vagrant/person-frontend-application/node_modules/.staging
155814 silly rollbackFailedOptional Starting
155815 silly rollbackFailedOptional Finishing
155816 silly runTopLevelLifecycles Finishing
155817 silly install printInstalled
155818 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
155819 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
155820 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
155820 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
155820 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
155820 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
155821 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
155822 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
155823 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
155823 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
155823 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
155823 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
155824 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
155825 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
155826 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
155826 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
155826 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
155826 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
155827 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/@angular/compiler-cli/node_modules/chokidar/node_modules/fsevents):
155828 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
155829 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
155829 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
155829 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
155829 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
155830 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/karma/node_modules/chokidar/node_modules/fsevents):
155831 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
155832 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
155832 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
155832 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
155832 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
155833 warn ngx-input-tag@0.0.5 requires a peer of @angular/core@^5.0.0 but none was installed.
155834 verbose If you need help, you may report this error at:
155834 verbose     <https://github.com/npm/npm/issues>
155835 warn ngx-input-tag@0.0.5 requires a peer of @angular/common@^5.0.0 but none was installed.
155836 verbose If you need help, you may report this error at:
155836 verbose     <https://github.com/npm/npm/issues>
155837 warn ngx-input-tag@0.0.5 requires a peer of @angular/forms@^5.0.0 but none was installed.
155838 verbose If you need help, you may report this error at:
155838 verbose     <https://github.com/npm/npm/issues>
155839 warn karma-jasmine-html-reporter@1.5.2 requires a peer of jasmine-core@>=3.5 but none was installed.
155840 verbose If you need help, you may report this error at:
155840 verbose     <https://github.com/npm/npm/issues>
155841 verbose stack Error: @angular/cli@8.2.2 postinstall: `node ./bin/postinstall/script.js`
155841 verbose stack Exit status 1
155841 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
155841 verbose stack     at emitTwo (events.js:106:13)
155841 verbose stack     at EventEmitter.emit (events.js:191:7)
155841 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
155841 verbose stack     at emitTwo (events.js:106:13)
155841 verbose stack     at ChildProcess.emit (events.js:191:7)
155841 verbose stack     at maybeClose (internal/child_process.js:920:16)
155841 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
155842 verbose pkgid @angular/cli@8.2.2
155843 verbose cwd /home/vagrant/person-frontend-application
155844 error Linux 3.10.0-957.5.1.el7.x86_64
155845 error argv "/usr/bin/node" "/usr/bin/npm" "install"
155846 error node v6.17.1
155847 error npm  v3.10.10
155848 error code ELIFECYCLE
155849 error @angular/cli@8.2.2 postinstall: `node ./bin/postinstall/script.js`
155849 error Exit status 1
155850 error Failed at the @angular/cli@8.2.2 postinstall script 'node ./bin/postinstall/script.js'.
155850 error Make sure you have the latest version of node.js and npm installed.
155850 error If you do, this is most likely a problem with the @angular/cli package,
155850 error not with npm itself.
155850 error Tell the author that this fails on your system:
155850 error     node ./bin/postinstall/script.js
155850 error You can get information on how to open an issue for this project with:
155850 error     npm bugs @angular/cli
155850 error Or if that isn't available, you can get their info via:
155850 error     npm owner ls @angular/cli
155850 error There is likely additional logging output above.
155851 verbose exit [ 1, true ]
[vagrant@localhost person-frontend-application]$

It looks promising and it would help that I get it to run, probably I'm missing something simple, can you tell me what it is? 

Best regards
Marc

**Comment by joenan** [comment]
Dear Marc
I have received your email and I am glad you have made an attempt to run it and will gladly assist you to see it run on your system. When I saw your message, the first thing I did was to get another system and run the application, and it ran successfully. Here are the steps again just incase you may have missed a step. 
1. Install node.js applicaiton on your system
2. Clone the app using the command  git clone https://github.com/joenan/person-frontend-application.git
After installing and cloning the app, then navigate to the directory of the cloned app and run the commands below 
3. npm install -g @angular/cli
4. npm install 
5. npm start
The command npm install -g @angular/cli will install angular latest stable angular cliThe Command npm install will install all the dependencies in the applicationThe command npm start will run the application in the default port 4200 and can be accessed via http://localhost:4200
Please keep me updated when you have followed these steps. I am looking forward to hearing from you. 

 
Regards,Nandom GusenTel: +234 806 0680 061, +234 805 2896 009Email: nandomgusen@yahoo.com, nandomgsn@gmail.comSkype: nandom.gusenWhatsapp: +2348060680061



 

    On Tuesday, February 18, 2020, 04:09:15 PM GMT+1, Joan Marc Riera Duocastella <notifications@github.com> wrote:  
 
 
Hi, I'm running inside the following Vagrant machine : https://github.com/joanmarcriera/vagrant-file-for-java-apps

The error shows as follows :

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/@angular/compiler-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/karma/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ngx-input-tag@0.0.5 requires a peer of @angular/core@^5.0.0 but none was installed.
npm WARN ngx-input-tag@0.0.5 requires a peer of @angular/common@^5.0.0 but none was installed.
npm WARN ngx-input-tag@0.0.5 requires a peer of @angular/forms@^5.0.0 but none was installed.
npm WARN karma-jasmine-html-reporter@1.5.2 requires a peer of jasmine-core@>=3.5 but none was installed.
npm ERR! Linux 3.10.0-957.5.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.17.1
npm ERR! npm v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! @angular/cli@8.2.2 postinstall: node ./bin/postinstall/script.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular/cli@8.2.2 postinstall script 'node ./bin/postinstall/script.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @angular/cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node ./bin/postinstall/script.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs @angular/cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls @angular/cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /home/vagrant/person-frontend-application/npm-debug.log
[vagrant@localhost person-frontend-application]$

The last lines from the debug file are :

155792 silly lifecycle socket.io@2.1.1

postinstall: yn@2.0.0
155795 silly lifecycle yn@2.0.0

postinstall: @angular-devkit/build-angular@0.802.2
155798 silly lifecycle @angular-devkit/build-angular@0.802.2

postinstall: @angular/animations@8.2.14
155801 silly lifecycle @angular/animations@8.2.14

postinstall: @angular/cdk@8.2.3
155804 silly lifecycle @angular/cdk@8.2.3

postinstall: @angular/cli@8.2.2
155807 verbose lifecycle @angular/cli@8.2.2
postinstall: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/vagrant/person-frontend-application/node_modules/@angular/cli/node_modules/.bin:/home/vagrant/person-frontend-application/node_modules/.bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.local/bin:/home/vagrant/bin
155809 verbose lifecycle @angular/cli@8.2.2
postinstall: Args: [ '-c', 'node ./bin/postinstall/script.js' ]
155811 silly lifecycle @angular/cli@8.2.2
postinstall: Failed to exec postinstall script
155813 verbose unlock done using /home/vagrant/.npm/_locks/staging-d8fb262d67f9f226.lock for /home/vagrant/person-frontend-application/node_modules/.staging
155814 silly rollbackFailedOptional Starting
155815 silly rollbackFailedOptional Finishing
155816 silly runTopLevelLifecycles Finishing
155817 silly install printInstalled
155818 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
155819 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
155820 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS: darwin
155820 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch: any
155820 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS: linux
155820 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
155821 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
155822 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
155823 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS: darwin
155823 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch: any
155823 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS: linux
155823 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
155824 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
155825 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
155826 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS: darwin
155826 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch: any
155826 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS: linux
155826 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
155827 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/@angular/compiler-cli/node_modules/chokidar/node_modules/fsevents):
155828 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
155829 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS: darwin
155829 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch: any
155829 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS: linux
155829 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
155830 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/karma/node_modules/chokidar/node_modules/fsevents):
155831 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
155832 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS: darwin
155832 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch: any
155832 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS: linux
155832 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
155833 warn ngx-input-tag@0.0.5 requires a peer of @angular/core@^5.0.0 but none was installed.
155834 verbose If you need help, you may report this error at:
155834 verbose https://github.com/npm/npm/issues
155835 warn ngx-input-tag@0.0.5 requires a peer of @angular/common@^5.0.0 but none was installed.
155836 verbose If you need help, you may report this error at:
155836 verbose https://github.com/npm/npm/issues
155837 warn ngx-input-tag@0.0.5 requires a peer of @angular/forms@^5.0.0 but none was installed.
155838 verbose If you need help, you may report this error at:
155838 verbose https://github.com/npm/npm/issues
155839 warn karma-jasmine-html-reporter@1.5.2 requires a peer of jasmine-core@>=3.5 but none was installed.
155840 verbose If you need help, you may report this error at:
155840 verbose https://github.com/npm/npm/issues
155841 verbose stack Error: @angular/cli@8.2.2 postinstall: node ./bin/postinstall/script.js
155841 verbose stack Exit status 1
155841 verbose stack at EventEmitter. (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
155841 verbose stack at emitTwo (events.js:106:13)
155841 verbose stack at EventEmitter.emit (events.js:191:7)
155841 verbose stack at ChildProcess. (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
155841 verbose stack at emitTwo (events.js:106:13)
155841 verbose stack at ChildProcess.emit (events.js:191:7)
155841 verbose stack at maybeClose (internal/child_process.js:920:16)
155841 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
155842 verbose pkgid @angular/cli@8.2.2
155843 verbose cwd /home/vagrant/person-frontend-application
155844 error Linux 3.10.0-957.5.1.el7.x86_64
155845 error argv "/usr/bin/node" "/usr/bin/npm" "install"
155846 error node v6.17.1
155847 error npm v3.10.10
155848 error code ELIFECYCLE
155849 error @angular/cli@8.2.2 postinstall: node ./bin/postinstall/script.js
155849 error Exit status 1
155850 error Failed at the @angular/cli@8.2.2 postinstall script 'node ./bin/postinstall/script.js'.
155850 error Make sure you have the latest version of node.js and npm installed.
155850 error If you do, this is most likely a problem with the @angular/cli package,
155850 error not with npm itself.
155850 error Tell the author that this fails on your system:
155850 error node ./bin/postinstall/script.js
155850 error You can get information on how to open an issue for this project with:
155850 error npm bugs @angular/cli
155850 error Or if that isn't available, you can get their info via:
155850 error npm owner ls @angular/cli
155850 error There is likely additional logging output above.
155851 verbose exit [ 1, true ]
[vagrant@localhost person-frontend-application]$

It looks promising and it would help that I get it to run, probably I'm missing something simple, can you tell me what it is?

Best regards
Marc
